export const WandCores = [
    'Basilisk Horn',
    'Dragon Heartstring',
    'Fairy Wing',
    'Jackalope Antler',
    'Parchment',
    'Phoenix Feather',
    'Unicorn Hair',
];

export const WandWoodTypes = [
    'Acacia',
    'Alder',
    'Apple',
    'Ash',
    'Aspen',
    'Beech',
    'Blackthorn',
    'Black Walnut',
    'Cedar',
    'Cherry',
    'Chestnut',
    'Cypress',
    'Dogwood',
    'Ebony',
    'Elder',
    'Elm',
    'English Oak',
    'Fir',
    'Hawthorn',
    'Hazel',
    'Holly',
    'Hornbeam',
    'Larch',
    'Laurel',
    'Maple',
    'Pear',
    'Pine',
    'Poplar',
    'Red Oak',
    'Redwood',
    'Rowan',
    'Silver Lime',
    'Spruce',
    'Sycamore',
    'Vine',
    'Walnut',
    'Willow',
    'Yew',
];
